__main__ 2020-04-22 22:36:03,350 start 16 :
 start

processing.get_files 2020-04-22 22:36:03,351 loadFiles 292 :
 Start loadFiles, 527e4afc-4598-400f-8536-afa5324f0ba4 root

google.auth.transport.requests 2020-04-22 22:36:03,353 __call__ 117 :
 Making request: POST https://oauth2.googleapis.com/token

urllib3.connectionpool 2020-04-22 22:36:03,358 _new_conn 817 :
 Starting new HTTPS connection (1): oauth2.googleapis.com

urllib3.connectionpool 2020-04-22 22:36:03,488 _make_request 393 :
 https://oauth2.googleapis.com:443 "POST /token HTTP/1.1" 200 None

asyncio 2020-04-22 22:36:03,490 __init__ 59 :
 Using selector: EpollSelector

processing.datutils.test_utils 2020-04-22 22:36:04,377 print_size 107 :
 

Memory usage: 108216 (kb)

processing.datutils.test_utils 2020-04-22 22:36:04,653 print_size 110 :
 /usr/lib/python3.8/tracemalloc.py:532: size=82.0 KiB (+81.9 KiB), count=1485 (+1484), average=57 B

processing.datutils.test_utils 2020-04-22 22:36:04,655 print_size 110 :
 /usr/lib/python3.8/inspect.py:744: size=0 B (-36.8 KiB), count=0 (-673)

processing.datutils.test_utils 2020-04-22 22:36:04,656 print_size 110 :
 /usr/lib/python3.8/sre_parse.py:220: size=0 B (-13.1 KiB), count=0 (-240)

processing.datutils.test_utils 2020-04-22 22:36:04,657 print_size 110 :
 /usr/lib/python3.8/sre_parse.py:529: size=0 B (-12.7 KiB), count=0 (-233)

processing.datutils.test_utils 2020-04-22 22:36:04,659 print_size 110 :
 /usr/lib/python3.8/sre_parse.py:599: size=0 B (-3472 B), count=0 (-62)

processing.datutils.test_utils 2020-04-22 22:36:04,661 print_size 110 :
 /usr/lib/python3.8/sre_parse.py:680: size=0 B (-3192 B), count=0 (-57)

processing.datutils.test_utils 2020-04-22 22:36:04,662 print_size 110 :
 /usr/lib/python3.8/sre_parse.py:618: size=0 B (-2800 B), count=0 (-50)

processing.datutils.test_utils 2020-04-22 22:36:04,664 print_size 110 :
 /usr/lib/python3.8/sre_parse.py:490: size=0 B (-2128 B), count=0 (-38)

processing.datutils.test_utils 2020-04-22 22:36:04,666 print_size 110 :
 /usr/lib/python3.8/sre_parse.py:840: size=0 B (-1968 B), count=0 (-32)

processing.datutils.test_utils 2020-04-22 22:36:04,667 print_size 110 :
 /usr/lib/python3.8/sre_parse.py:567: size=0 B (-1848 B), count=0 (-33)

processing.datutils.test_utils 2020-04-22 22:36:04,704 print_size 118 :
 /home/henry/pydocs/data/527e4afc-4598-400f-8536-afa5324f0ba4/
0/0 at 2020-04-22 22:36:04.704489
dumped: 0

processing.datutils.test_utils 2020-04-22 22:36:04,705 print_size 121 :
 BEGIN2020-04-22 22:36:03.306366


asyncio 2020-04-22 22:36:04,708 _run_once 1854 :
 Executing <Task pending name='Task-23' coro=<TestUtil.print_size() running at /home/henry/pydocs/processing/datutils/test_utils.py:141> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f5d38135eb0>()] created at /usr/lib/python3.8/asyncio/base_events.py:422> created at /home/henry/pydocs/processing/get_files.py:251> took 0.339 seconds

processing.get_files 2020-04-22 22:36:04,710 getRevision 197 :
 getRevision looping

processing.datutils.test_utils 2020-04-22 22:36:04,711 tryGetQueue 195 :
 getRevisionwaiting 1 2

processing.get_files 2020-04-22 22:36:04,714 getIdsRecursive 86 :
 getIdsRecursive looping

processing.get_files 2020-04-22 22:36:04,716 getIdsRecursive 86 :
 getIdsRecursive looping

processing.get_files 2020-04-22 22:36:04,717 getIdsRecursive 86 :
 getIdsRecursive looping

asyncio 2020-04-22 22:36:04,762 _getaddrinfo_debug 805 :
 Get address info www.googleapis.com:443, type=<SocketKind.SOCK_STREAM: 1>

asyncio 2020-04-22 22:36:04,783 _getaddrinfo_debug 815 :
 Getting address info www.googleapis.com:443, type=<SocketKind.SOCK_STREAM: 1> took 21.312ms: [(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('216.58.217.42', 443)), (<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('2607:f8b0:400a:803::200a', 443, 0, 0))]

asyncio 2020-04-22 22:36:04,808 _start_handshake 603 :
 <asyncio.sslproto.SSLProtocol object at 0x7f5d37aaacd0> starts SSL handshake

processing.get_files 2020-04-22 22:36:04,833 getIdsRecursive 86 :
 getIdsRecursive looping

asyncio 2020-04-22 22:36:04,837 _on_handshake_complete 647 :
 <asyncio.sslproto.SSLProtocol object at 0x7f5d37aaacd0>: SSL handshake took 29.1 ms

asyncio 2020-04-22 22:36:04,838 create_connection 1057 :
 <asyncio.TransportSocket fd=11, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.19.38.9', 56454), raddr=('216.58.217.42', 443)> connected to 216.58.217.42:443: (<asyncio.sslproto._SSLProtocolTransport object at 0x7f5d375b4b20>, <aiohttp.client_proto.ResponseHandler object at 0x7f5d5ac27520>)

processing.get_files 2020-04-22 22:36:04,950 getIdsRecursive 86 :
 getIdsRecursive looping

processing.datutils.test_utils 2020-04-22 22:36:04,991 tryGetQueue 195 :
 getIdswaiting 1 2

processing.datutils.test_utils 2020-04-22 22:36:05,007 tryGetQueue 195 :
 getIdswaiting 1 2

processing.datutils.test_utils 2020-04-22 22:36:05,115 tryGetQueue 195 :
 getIdswaiting 1 2

processing.get_files 2020-04-22 22:36:05,127 getIdsRecursive 86 :
 getIdsRecursive looping

processing.datutils.test_utils 2020-04-22 22:36:05,170 tryGetQueue 195 :
 getIdswaiting 1 2

processing.get_files 2020-04-22 22:36:05,174 getIdsRecursive 86 :
 getIdsRecursive looping

processing.get_files 2020-04-22 22:36:05,264 getIdsRecursive 86 :
 getIdsRecursive looping

processing.datutils.test_utils 2020-04-22 22:36:05,316 tryGetQueue 195 :
 getIdswaiting 1 2

processing.get_files 2020-04-22 22:36:05,339 getIdsRecursive 86 :
 getIdsRecursive looping

processing.get_files 2020-04-22 22:36:05,356 getIdsRecursive 86 :
 getIdsRecursive looping

processing.datutils.test_utils 2020-04-22 22:36:05,421 tryGetQueue 195 :
 getIdswaiting 1 2

processing.datutils.test_utils 2020-04-22 22:36:05,606 tryGetQueue 195 :
 getIdswaiting 1 2

processing.get_files 2020-04-22 22:36:05,610 getRevision 197 :
 getRevision looping

processing.datutils.test_utils 2020-04-22 22:36:05,612 tryGetQueue 195 :
 getRevisionwaiting 1 2

processing.datutils.test_utils 2020-04-22 22:36:05,624 tryGetQueue 195 :
 getIdswaiting 1 2

processing.datutils.test_utils 2020-04-22 22:36:05,667 tryGetQueue 195 :
 getIdswaiting 1 2

processing.get_files 2020-04-22 22:36:05,803 getIdsRecursive 86 :
 getIdsRecursive looping

processing.get_files 2020-04-22 22:36:06,421 getRevision 197 :
 getRevision looping

processing.get_files 2020-04-22 22:36:06,449 getIdsRecursive 86 :
 getIdsRecursive looping

processing.get_files 2020-04-22 22:36:06,645 getRevision 197 :
 getRevision looping

processing.get_files 2020-04-22 22:36:06,749 getRevision 197 :
 getRevision looping

processing.get_files 2020-04-22 22:36:07,037 getIdsRecursive 86 :
 getIdsRecursive looping

processing.get_files 2020-04-22 22:36:07,467 getIdsRecursive 86 :
 getIdsRecursive looping

processing.get_files 2020-04-22 22:36:07,723 getRevision 197 :
 getRevision looping

processing.get_files 2020-04-22 22:36:08,074 getIdsRecursive 86 :
 getIdsRecursive looping

processing.get_files 2020-04-22 22:36:08,175 getRevision 197 :
 getRevision looping

processing.get_files 2020-04-22 22:36:08,822 getIdsRecursive 86 :
 getIdsRecursive looping

processing.get_files 2020-04-22 22:36:09,070 getRevision 197 :
 getRevision looping

processing.get_files 2020-04-22 22:36:09,525 getIdsRecursive 86 :
 getIdsRecursive looping

processing.get_files 2020-04-22 22:36:09,732 getRevision 197 :
 getRevision looping

processing.get_files 2020-04-22 22:36:10,046 getIdsRecursive 86 :
 getIdsRecursive looping

processing.get_files 2020-04-22 22:36:10,283 getRevision 197 :
 getRevision looping

processing.get_files 2020-04-22 22:36:10,363 getRevision 209 :
 not google doc

asyncio 2020-04-22 22:36:10,410 _start_handshake 603 :
 <asyncio.sslproto.SSLProtocol object at 0x7f5d3782dc10> starts SSL handshake

asyncio 2020-04-22 22:36:10,413 _start_handshake 603 :
 <asyncio.sslproto.SSLProtocol object at 0x7f5d3782dd90> starts SSL handshake

asyncio 2020-04-22 22:36:10,415 _start_handshake 603 :
 <asyncio.sslproto.SSLProtocol object at 0x7f5d3782df70> starts SSL handshake

asyncio 2020-04-22 22:36:10,437 _on_handshake_complete 647 :
 <asyncio.sslproto.SSLProtocol object at 0x7f5d3782dc10>: SSL handshake took 26.9 ms

asyncio 2020-04-22 22:36:10,438 create_connection 1057 :
 <asyncio.TransportSocket fd=12, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.19.38.9', 56456), raddr=('216.58.217.42', 443)> connected to 216.58.217.42:443: (<asyncio.sslproto._SSLProtocolTransport object at 0x7f5d3781bac0>, <aiohttp.client_proto.ResponseHandler object at 0x7f5d3755c1c0>)

asyncio 2020-04-22 22:36:10,443 _on_handshake_complete 647 :
 <asyncio.sslproto.SSLProtocol object at 0x7f5d3782dd90>: SSL handshake took 29.5 ms

asyncio 2020-04-22 22:36:10,444 create_connection 1057 :
 <asyncio.TransportSocket fd=13, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.19.38.9', 56458), raddr=('216.58.217.42', 443)> connected to 216.58.217.42:443: (<asyncio.sslproto._SSLProtocolTransport object at 0x7f5d3781bca0>, <aiohttp.client_proto.ResponseHandler object at 0x7f5d3781b4c0>)

asyncio 2020-04-22 22:36:10,447 _on_handshake_complete 647 :
 <asyncio.sslproto.SSLProtocol object at 0x7f5d3782df70>: SSL handshake took 31.8 ms

asyncio 2020-04-22 22:36:10,448 create_connection 1057 :
 <asyncio.TransportSocket fd=14, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.19.38.9', 56460), raddr=('216.58.217.42', 443)> connected to 216.58.217.42:443: (<asyncio.sslproto._SSLProtocolTransport object at 0x7f5d3781be20>, <aiohttp.client_proto.ResponseHandler object at 0x7f5d3782c760>)

processing.get_files 2020-04-22 22:36:10,539 getIdsRecursive 86 :
 getIdsRecursive looping

processing.get_files 2020-04-22 22:36:10,615 getRevision 209 :
 not google doc

processing.get_files 2020-04-22 22:36:10,710 queryDriveActivity 167 :
 EXCEPTION
Traceback (most recent call last):
  File "/home/henry/pydocs/processing/datutils/test_utils.py", line 155, in handleResponse
    assert response.status == 200, "Response not 200"
AssertionError: Response not 200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/henry/pydocs/processing/get_files.py", line 150, in queryDriveActivity
    code = await TestUtil.handleResponse(revResponse, fileTuple,queue = files)
  File "/home/henry/pydocs/processing/datutils/test_utils.py", line 158, in handleResponse
    e = sys.exc_info()[0]
NameError: name 'sys' is not defined
processing.get_files 2020-04-22 22:36:10,712 queryDriveActivity 169 :
 Because of exception, sleeping for 5

asyncio 2020-04-22 22:36:10,730 _start_handshake 603 :
 <asyncio.sslproto.SSLProtocol object at 0x7f5d3782dcd0> starts SSL handshake

root 2020-04-22 22:36:10,741 handle_exception 74 :
 Custom Uncaught exception
Traceback (most recent call last):
  File "dsds.py", line 34, in <module>
    start()
  File "dsds.py", line 31, in start
    loadFiles(uid, workingPath, fileid, creds)
  File "/home/henry/pydocs/processing/get_files.py", line 317, in loadFiles
    loop.run_until_complete(asyncio.gather(startTask))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/henry/pydocs/processing/get_files.py", line 255, in start
    await asyncio.gather(*revisionExplorer)
  File "/home/henry/pydocs/processing/get_files.py", line 214, in getRevision
    await gd.async_init(fileId, session, headers)
  File "/home/henry/pydocs/processing/gdoc.py", line 14, in async_init
    await self.get_last_revision()
  File "/home/henry/pydocs/processing/gdoc.py", line 21, in get_last_revision
    code = await TestUtil.handleResponse(response)
NameError: name 'TestUtil' is not defined
root 2020-04-22 22:36:12,283 handle_exception 78 :
 exiting! from sshook

root 2020-04-22 22:36:12,284 handle_exception 80 :
 sending to default hook

