base.py:01,17:45:49:__connect:653:oSqFqA -- Created new connection <pyodbc.Connection object at 0x7f0b44bbde30>
base.py:01,17:45:49:_execute_context:1205:oSqFqA -- SELECT CAST(SERVERPROPERTY('ProductVersion') AS VARCHAR)
base.py:01,17:45:49:_execute_context:1207:oSqFqA -- ()
result.p:01,17:45:50:_init_metadata:809:oSqFqA -- Col ('',)
result.p:01,17:45:50:process_rows:1249:oSqFqA -- Row ('12.0.2000.8',)
base.py:01,17:45:50:_execute_context:1205:oSqFqA -- SELECT schema_name()
base.py:01,17:45:50:_execute_context:1207:oSqFqA -- ()
result.p:01,17:45:50:_init_metadata:809:oSqFqA -- Col ('',)
result.p:01,17:45:50:process_rows:1249:oSqFqA -- Row ('dbo',)
base.py:01,17:45:51:_cursor_execute:1311:oSqFqA -- SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
base.py:01,17:45:51:_cursor_execute:1312:oSqFqA -- ()
base.py:01,17:45:51:_cursor_execute:1311:oSqFqA -- SELECT CAST('test unicode returns' AS NVARCHAR(60)) AS anon_1
base.py:01,17:45:51:_cursor_execute:1312:oSqFqA -- ()
base.py:01,17:45:53:checkout:507:oSqFqA -- Connection <pyodbc.Connection object at 0x7f0b44bbde30> checked out from pool
base.py:01,17:45:53:_execute_context:1205:oSqFqA -- SELECT [INFORMATION_SCHEMA].[COLUMNS].[TABLE_SCHEMA], [INFORMATION_SCHEMA].[COLUMNS].[TABLE_NAME], [INFORMATION_SCHEMA].[COLUMNS].[COLUMN_NAME], [INFORMATION_SCHEMA].[COLUMNS].[IS_NULLABLE], [INFORMATION_SCHEMA].[COLUMNS].[DATA_TYPE], [INFORMATION_SCHEMA].[COLUMNS].[ORDINAL_POSITION], [INFORMATION_SCHEMA].[COLUMNS].[CHARACTER_MAXIMUM_LENGTH], [INFORMATION_SCHEMA].[COLUMNS].[NUMERIC_PRECISION], [INFORMATION_SCHEMA].[COLUMNS].[NUMERIC_SCALE], [INFORMATION_SCHEMA].[COLUMNS].[COLUMN_DEFAULT], [INFORMATION_SCHEMA].[COLUMNS].[COLLATION_NAME] 
FROM [INFORMATION_SCHEMA].[COLUMNS] 
WHERE [INFORMATION_SCHEMA].[COLUMNS].[TABLE_NAME] = CAST(? AS NVARCHAR(max)) AND [INFORMATION_SCHEMA].[COLUMNS].[TABLE_SCHEMA] = CAST(? AS NVARCHAR(max))
base.py:01,17:45:53:_execute_context:1207:oSqFqA -- ('files', 'dbo')
result.p:01,17:45:54:_init_metadata:809:oSqFqA -- Col ('TABLE_SCHEMA', 'TABLE_NAME', 'COLUMN_NAME', 'IS_NULLABLE', 'DATA_TYPE', 'ORDINAL_POSITION', 'CHARACTER_MAXIMUM_LENGTH', 'NUMERIC_PRECISION', 'NUMERIC_SCALE', 'COLUMN_DEFAULT', 'COLLATION_NAME')
result.p:01,17:45:54:process_rows:1249:oSqFqA -- Row ('dbo', 'files', 'id', 'NO', 'int', 1, None, 10, 0, None, None)
base.py:01,17:45:54:_execute_context:1205:oSqFqA -- SELECT [INFORMATION_SCHEMA].[COLUMNS].[TABLE_SCHEMA], [INFORMATION_SCHEMA].[COLUMNS].[TABLE_NAME], [INFORMATION_SCHEMA].[COLUMNS].[COLUMN_NAME], [INFORMATION_SCHEMA].[COLUMNS].[IS_NULLABLE], [INFORMATION_SCHEMA].[COLUMNS].[DATA_TYPE], [INFORMATION_SCHEMA].[COLUMNS].[ORDINAL_POSITION], [INFORMATION_SCHEMA].[COLUMNS].[CHARACTER_MAXIMUM_LENGTH], [INFORMATION_SCHEMA].[COLUMNS].[NUMERIC_PRECISION], [INFORMATION_SCHEMA].[COLUMNS].[NUMERIC_SCALE], [INFORMATION_SCHEMA].[COLUMNS].[COLUMN_DEFAULT], [INFORMATION_SCHEMA].[COLUMNS].[COLLATION_NAME] 
FROM [INFORMATION_SCHEMA].[COLUMNS] 
WHERE [INFORMATION_SCHEMA].[COLUMNS].[TABLE_NAME] = CAST(? AS NVARCHAR(max)) AND [INFORMATION_SCHEMA].[COLUMNS].[TABLE_SCHEMA] = CAST(? AS NVARCHAR(max))
base.py:01,17:45:54:_execute_context:1207:oSqFqA -- ('owner', 'dbo')
result.p:01,17:45:55:_init_metadata:809:oSqFqA -- Col ('TABLE_SCHEMA', 'TABLE_NAME', 'COLUMN_NAME', 'IS_NULLABLE', 'DATA_TYPE', 'ORDINAL_POSITION', 'CHARACTER_MAXIMUM_LENGTH', 'NUMERIC_PRECISION', 'NUMERIC_SCALE', 'COLUMN_DEFAULT', 'COLLATION_NAME')
result.p:01,17:45:55:process_rows:1249:oSqFqA -- Row ('dbo', 'owner', 'id', 'NO', 'int', 1, None, 10, 0, None, None)
base.py:01,17:45:55:_execute_context:1205:oSqFqA -- SELECT [INFORMATION_SCHEMA].[COLUMNS].[TABLE_SCHEMA], [INFORMATION_SCHEMA].[COLUMNS].[TABLE_NAME], [INFORMATION_SCHEMA].[COLUMNS].[COLUMN_NAME], [INFORMATION_SCHEMA].[COLUMNS].[IS_NULLABLE], [INFORMATION_SCHEMA].[COLUMNS].[DATA_TYPE], [INFORMATION_SCHEMA].[COLUMNS].[ORDINAL_POSITION], [INFORMATION_SCHEMA].[COLUMNS].[CHARACTER_MAXIMUM_LENGTH], [INFORMATION_SCHEMA].[COLUMNS].[NUMERIC_PRECISION], [INFORMATION_SCHEMA].[COLUMNS].[NUMERIC_SCALE], [INFORMATION_SCHEMA].[COLUMNS].[COLUMN_DEFAULT], [INFORMATION_SCHEMA].[COLUMNS].[COLLATION_NAME] 
FROM [INFORMATION_SCHEMA].[COLUMNS] 
WHERE [INFORMATION_SCHEMA].[COLUMNS].[TABLE_NAME] = CAST(? AS NVARCHAR(max)) AND [INFORMATION_SCHEMA].[COLUMNS].[TABLE_SCHEMA] = CAST(? AS NVARCHAR(max))
base.py:01,17:45:55:_execute_context:1207:oSqFqA -- ('dates', 'dbo')
result.p:01,17:45:58:_init_metadata:809:oSqFqA -- Col ('TABLE_SCHEMA', 'TABLE_NAME', 'COLUMN_NAME', 'IS_NULLABLE', 'DATA_TYPE', 'ORDINAL_POSITION', 'CHARACTER_MAXIMUM_LENGTH', 'NUMERIC_PRECISION', 'NUMERIC_SCALE', 'COLUMN_DEFAULT', 'COLLATION_NAME')
result.p:01,17:45:58:process_rows:1249:oSqFqA -- Row ('dbo', 'dates', 'id', 'NO', 'int', 1, None, 10, 0, None, None)
base.py:01,17:46:00:_execute_context:1205:oSqFqA -- SELECT [INFORMATION_SCHEMA].[COLUMNS].[TABLE_SCHEMA], [INFORMATION_SCHEMA].[COLUMNS].[TABLE_NAME], [INFORMATION_SCHEMA].[COLUMNS].[COLUMN_NAME], [INFORMATION_SCHEMA].[COLUMNS].[IS_NULLABLE], [INFORMATION_SCHEMA].[COLUMNS].[DATA_TYPE], [INFORMATION_SCHEMA].[COLUMNS].[ORDINAL_POSITION], [INFORMATION_SCHEMA].[COLUMNS].[CHARACTER_MAXIMUM_LENGTH], [INFORMATION_SCHEMA].[COLUMNS].[NUMERIC_PRECISION], [INFORMATION_SCHEMA].[COLUMNS].[NUMERIC_SCALE], [INFORMATION_SCHEMA].[COLUMNS].[COLUMN_DEFAULT], [INFORMATION_SCHEMA].[COLUMNS].[COLLATION_NAME] 
FROM [INFORMATION_SCHEMA].[COLUMNS] 
WHERE [INFORMATION_SCHEMA].[COLUMNS].[TABLE_NAME] = CAST(? AS NVARCHAR(max)) AND [INFORMATION_SCHEMA].[COLUMNS].[TABLE_SCHEMA] = CAST(? AS NVARCHAR(max))
base.py:01,17:46:00:_execute_context:1207:oSqFqA -- ('closure', 'dbo')
result.p:01,17:46:00:_init_metadata:809:oSqFqA -- Col ('TABLE_SCHEMA', 'TABLE_NAME', 'COLUMN_NAME', 'IS_NULLABLE', 'DATA_TYPE', 'ORDINAL_POSITION', 'CHARACTER_MAXIMUM_LENGTH', 'NUMERIC_PRECISION', 'NUMERIC_SCALE', 'COLUMN_DEFAULT', 'COLLATION_NAME')
result.p:01,17:46:00:process_rows:1249:oSqFqA -- Row ('dbo', 'closure', 'id', 'NO', 'int', 1, None, 10, 0, None, None)
base.py:01,17:46:01:_execute_context:1205:oSqFqA -- SELECT [INFORMATION_SCHEMA].[COLUMNS].[TABLE_SCHEMA], [INFORMATION_SCHEMA].[COLUMNS].[TABLE_NAME], [INFORMATION_SCHEMA].[COLUMNS].[COLUMN_NAME], [INFORMATION_SCHEMA].[COLUMNS].[IS_NULLABLE], [INFORMATION_SCHEMA].[COLUMNS].[DATA_TYPE], [INFORMATION_SCHEMA].[COLUMNS].[ORDINAL_POSITION], [INFORMATION_SCHEMA].[COLUMNS].[CHARACTER_MAXIMUM_LENGTH], [INFORMATION_SCHEMA].[COLUMNS].[NUMERIC_PRECISION], [INFORMATION_SCHEMA].[COLUMNS].[NUMERIC_SCALE], [INFORMATION_SCHEMA].[COLUMNS].[COLUMN_DEFAULT], [INFORMATION_SCHEMA].[COLUMNS].[COLLATION_NAME] 
FROM [INFORMATION_SCHEMA].[COLUMNS] 
WHERE [INFORMATION_SCHEMA].[COLUMNS].[TABLE_NAME] = CAST(? AS NVARCHAR(max)) AND [INFORMATION_SCHEMA].[COLUMNS].[TABLE_SCHEMA] = CAST(? AS NVARCHAR(max))
base.py:01,17:46:01:_execute_context:1207:oSqFqA -- ('filename', 'dbo')
result.p:01,17:46:03:_init_metadata:809:oSqFqA -- Col ('TABLE_SCHEMA', 'TABLE_NAME', 'COLUMN_NAME', 'IS_NULLABLE', 'DATA_TYPE', 'ORDINAL_POSITION', 'CHARACTER_MAXIMUM_LENGTH', 'NUMERIC_PRECISION', 'NUMERIC_SCALE', 'COLUMN_DEFAULT', 'COLLATION_NAME')
result.p:01,17:46:03:process_rows:1249:oSqFqA -- Row ('dbo', 'filename', 'id', 'NO', 'int', 1, None, 10, 0, None, None)
base.py:01,17:46:03:_execute_context:1205:oSqFqA -- SELECT [INFORMATION_SCHEMA].[COLUMNS].[TABLE_SCHEMA], [INFORMATION_SCHEMA].[COLUMNS].[TABLE_NAME], [INFORMATION_SCHEMA].[COLUMNS].[COLUMN_NAME], [INFORMATION_SCHEMA].[COLUMNS].[IS_NULLABLE], [INFORMATION_SCHEMA].[COLUMNS].[DATA_TYPE], [INFORMATION_SCHEMA].[COLUMNS].[ORDINAL_POSITION], [INFORMATION_SCHEMA].[COLUMNS].[CHARACTER_MAXIMUM_LENGTH], [INFORMATION_SCHEMA].[COLUMNS].[NUMERIC_PRECISION], [INFORMATION_SCHEMA].[COLUMNS].[NUMERIC_SCALE], [INFORMATION_SCHEMA].[COLUMNS].[COLUMN_DEFAULT], [INFORMATION_SCHEMA].[COLUMNS].[COLLATION_NAME] 
FROM [INFORMATION_SCHEMA].[COLUMNS] 
WHERE [INFORMATION_SCHEMA].[COLUMNS].[TABLE_NAME] = CAST(? AS NVARCHAR(max)) AND [INFORMATION_SCHEMA].[COLUMNS].[TABLE_SCHEMA] = CAST(? AS NVARCHAR(max))
base.py:01,17:46:03:_execute_context:1207:oSqFqA -- ('tasks', 'dbo')
result.p:01,17:46:04:_init_metadata:809:oSqFqA -- Col ('TABLE_SCHEMA', 'TABLE_NAME', 'COLUMN_NAME', 'IS_NULLABLE', 'DATA_TYPE', 'ORDINAL_POSITION', 'CHARACTER_MAXIMUM_LENGTH', 'NUMERIC_PRECISION', 'NUMERIC_SCALE', 'COLUMN_DEFAULT', 'COLLATION_NAME')
result.p:01,17:46:04:process_rows:1249:oSqFqA -- Row ('dbo', 'tasks', 'id', 'NO', 'int', 1, None, 10, 0, None, None)
base.py:01,17:46:04:_finalize_fairy:684:oSqFqA -- Connection <pyodbc.Connection object at 0x7f0b44bbde30> being returned to pool
base.py:01,17:46:04:_reset:872:oSqFqA -- Connection <pyodbc.Connection object at 0x7f0b44bbde30> rollback-on-return
callback:01,17:46:05:<module>:33:oSqFqA -- DASH CALLBACKS IMPORTED
base.py:01,17:46:05:checkout:507:oSqFqA -- Connection <pyodbc.Connection object at 0x7f0b44bbde30> checked out from pool
base.py:01,17:46:05:_begin_impl:711:oSqFqA -- BEGIN (implicit)
base.py:01,17:46:05:_execute_context:1205:oSqFqA -- SELECT anon_1.id AS anon_1_id, anon_1.count AS anon_1_count, filename.[fileName] AS [filename_fileName], files.[lastModDate] AS [files_lastModDate] 
FROM (SELECT anon_2.id AS id, sum(anon_2.va) AS count 
FROM (SELECT files.id AS id, dates.date AS va 
FROM files JOIN dates ON files.id = dates.[fileId] JOIN owner ON owner.id = files.parent_id 
WHERE owner.id = ?) AS anon_2 GROUP BY anon_2.id) AS anon_1 JOIN filename ON filename.[fileId] = anon_1.id JOIN files ON files.id = anon_1.id
base.py:01,17:46:05:_execute_context:1207:oSqFqA -- (2694,)
configlo:01,17:46:54:handle_exception:84:oSqFqA -- Custom Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3.8/encodings/utf_16_le.py", line 15, in decode
    def decode(input, errors='strict'):
KeyboardInterrupt

The above exception was the direct cause of the following exception:

KeyboardInterrupt: decoding with 'utf-16le' codec failed (KeyboardInterrupt: )

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run.py", line 28, in <module>
    app = create_flask_serv()
  File "/home/henry/pydocs/flaskr/__init__.py", line 16, in create_flask_serv
    register_dashapp(flask_serv)
  File "/home/henry/pydocs/flaskr/dashapp/__init__.py", line 29, in register_dashapp
    dashapp.layout = layout()
  File "/home/henry/pydocs/flaskr/dashapp/layout.py", line 18, in layout
    figure=gen_fListFig(scoped_sess, test["userid"])
  File "/home/henry/pydocs/flaskr/dashapp/dash_functions.py", line 115, in gen_fListFig
    fListFig = getNormalBubbleData(sess, userid)
  File "/home/henry/pydocs/flaskr/dashapp/dash_functions.py", line 70, in getNormalBubbleData
    count = sess.query(times.c.id, times.c.count, Filename.fileName, Files.lastModDate).join(Filename, Filename.fileId == times.c.id) \
  File "/home/henry/.virtualenvs/pydocs/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3246, in all
    return list(self)
  File "/home/henry/.virtualenvs/pydocs/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3405, in __iter__
    return self._execute_and_instances(context)
  File "/home/henry/.virtualenvs/pydocs/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3430, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/henry/.virtualenvs/pydocs/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 984, in execute
    return meth(self, multiparams, params)
  File "/home/henry/.virtualenvs/pydocs/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/henry/.virtualenvs/pydocs/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1097, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/henry/.virtualenvs/pydocs/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1287, in _execute_context
    self._handle_dbapi_exception(
  File "/home/henry/.virtualenvs/pydocs/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1485, in _handle_dbapi_exception
    util.raise_(exc_info[1], with_traceback=exc_info[2])
  File "/home/henry/.virtualenvs/pydocs/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/henry/.virtualenvs/pydocs/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1247, in _execute_context
    self.dialect.do_execute(
  File "/home/henry/.virtualenvs/pydocs/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
SystemError: <class 'pyodbc.Error'> returned a result with an error set
configlo:01,17:46:54:mp_sendmail:121:oSqFqA -- sending mail
configlo:01,17:47:00:handle_exception:87:oSqFqA -- exiting! from sshook
