sql.py:25,13:23:14:<module>:24:YNTwNQ -- Driver%3D%7BODBC+Driver+17+for+SQL+Server%7D%3BServer%3Dtcp%3Apydoc-db.database.windows.net%2C1433%3BDatabase%3Dpydoc-db%3BUid%3Dhenry2833%3BPwd%3D%7BInfoip32%7D%3BEncrypt%3Dyes%3BTrustServerCertificate%3Dno%3BConnection+Timeout%3D30%3B
dsds.py:25,13:23:16:start:18:YNTwNQ -- start
get_file:25,13:23:16:loadFiles:267:YNTwNQ -- Start loadFiles, 527e4afc-4598-400f-8536-afa5324f0ba4 1ytJocI9f4gvmpnwLNNfpQzRPhcFs5EzR
requests:25,13:23:16:__call__:117:YNTwNQ -- Making request: POST https://oauth2.googleapis.com/token
connecti:25,13:23:16:_new_conn:817:YNTwNQ -- Starting new HTTPS connection (1): oauth2.googleapis.com
connecti:25,13:23:16:_make_request:393:YNTwNQ -- https://oauth2.googleapis.com:443 "POST /token HTTP/1.1" 200 None
selector:25,13:23:16:__init__:59:YNTwNQ -- Using selector: EpollSelector
test_uti:25,13:23:16:print_size:82:YNTwNQ -- ---------------Memory usage: 94532 (kb)---------------0 mins since start
test_uti:25,13:23:17:print_size:100:YNTwNQ -- /home/henry/pydocs/data/527e4afc-4598-400f-8536-afa5324f0ba4/
0/0 at 2020-04-25 13:23:17.005242
dumped: 0
get_file:25,13:23:17:getIdsRecursive:53:YNTwNQ -- getIdsRecursive looping
get_file:25,13:23:17:getIdsRecursive:53:YNTwNQ -- getIdsRecursive looping
test_uti:25,13:23:17:tryGetQueue:211:YNTwNQ -- getIdswaiting 1 1
get_file:25,13:23:17:getIdsRecursive:53:YNTwNQ -- getIdsRecursive looping
get_file:25,13:23:17:getIdsRecursive:53:YNTwNQ -- getIdsRecursive looping
test_uti:25,13:23:17:tryGetQueue:211:YNTwNQ -- getIdswaiting 1 1
test_uti:25,13:23:17:tryGetQueue:211:YNTwNQ -- getIdswaiting 1 1
test_uti:25,13:23:18:print_size:82:YNTwNQ -- ---------------Memory usage: 94716 (kb)---------------0 mins since start
test_uti:25,13:23:18:print_size:100:YNTwNQ -- /home/henry/pydocs/data/527e4afc-4598-400f-8536-afa5324f0ba4/
0/3 at 2020-04-25 13:23:18.036517
dumped: 0
get_file:25,13:23:18:getRevision:164:YNTwNQ -- getRevision looping
gdoc.py:25,13:23:18:async_init:24:YNTwNQ -- async init called
get_file:25,13:23:18:getRevision:164:YNTwNQ -- getRevision looping
gdoc.py:25,13:23:18:async_init:24:YNTwNQ -- async init called
gdoc.py:25,13:23:18:get_last_revision:54:YNTwNQ -- last revision id 546
gdoc.py:25,13:23:18:async_init:31:YNTwNQ -- after await 546
gdoc.py:25,13:23:18:get_last_revision:54:YNTwNQ -- last revision id 2502
gdoc.py:25,13:23:18:async_init:31:YNTwNQ -- after await 2502
get_file:25,13:23:18:getRevision:188:YNTwNQ -- google doc
get_file:25,13:23:18:getRevision:164:YNTwNQ -- getRevision looping
test_uti:25,13:23:19:print_size:82:YNTwNQ -- ---------------Memory usage: 96512 (kb)---------------0 mins since start
test_uti:25,13:23:19:print_size:100:YNTwNQ -- /home/henry/pydocs/data/527e4afc-4598-400f-8536-afa5324f0ba4/
1/2 at 2020-04-25 13:23:19.066161
dumped: 0
get_file:25,13:23:19:getRevision:188:YNTwNQ -- google doc
get_file:25,13:23:19:getRevision:164:YNTwNQ -- getRevision looping
get_file:25,13:23:19:getRevision:164:YNTwNQ -- getRevision looping
test_uti:25,13:23:20:print_size:82:YNTwNQ -- ---------------Memory usage: 101532 (kb)---------------0 mins since start
test_uti:25,13:23:20:print_size:100:YNTwNQ -- /home/henry/pydocs/data/527e4afc-4598-400f-8536-afa5324f0ba4/
2/3 at 2020-04-25 13:23:20.096946
dumped: 0
test_uti:25,13:23:21:print_size:82:YNTwNQ -- ---------------Memory usage: 101532 (kb)---------------0 mins since start
test_uti:25,13:23:21:print_size:100:YNTwNQ -- /home/henry/pydocs/data/527e4afc-4598-400f-8536-afa5324f0ba4/
2/3 at 2020-04-25 13:23:21.129148
dumped: 0
test_uti:25,13:23:22:print_size:82:YNTwNQ -- ---------------Memory usage: 101532 (kb)---------------0 mins since start
test_uti:25,13:23:22:print_size:100:YNTwNQ -- /home/henry/pydocs/data/527e4afc-4598-400f-8536-afa5324f0ba4/
2/3 at 2020-04-25 13:23:22.159014
dumped: 0
gdoc.py:25,13:23:22:async_init:24:YNTwNQ -- async init called
test_uti:25,13:23:22:tryGetQueue:211:YNTwNQ -- getRevisionwaiting 1 1
test_uti:25,13:23:22:tryGetQueue:211:YNTwNQ -- getRevisionwaiting 1 1
test_uti:25,13:23:23:print_size:82:YNTwNQ -- ---------------Memory usage: 101532 (kb)---------------0 mins since start
test_uti:25,13:23:23:print_size:100:YNTwNQ -- /home/henry/pydocs/data/527e4afc-4598-400f-8536-afa5324f0ba4/
2/2 at 2020-04-25 13:23:23.187806
dumped: 0
gdoc.py:25,13:23:23:get_last_revision:54:YNTwNQ -- last revision id 647
gdoc.py:25,13:23:23:async_init:31:YNTwNQ -- after await 647
get_file:25,13:23:23:getRevision:188:YNTwNQ -- google doc
get_file:25,13:23:23:getRevision:164:YNTwNQ -- getRevision looping
test_uti:25,13:23:24:print_size:82:YNTwNQ -- ---------------Memory usage: 101532 (kb)---------------0 mins since start
test_uti:25,13:23:24:print_size:100:YNTwNQ -- /home/henry/pydocs/data/527e4afc-4598-400f-8536-afa5324f0ba4/
3/3 at 2020-04-25 13:23:24.217984
dumped: 0
get_file:25,13:23:24:getRevision:164:YNTwNQ -- getRevision looping
test_uti:25,13:23:25:print_size:82:YNTwNQ -- ---------------Memory usage: 101532 (kb)---------------0 mins since start
test_uti:25,13:23:25:print_size:100:YNTwNQ -- /home/henry/pydocs/data/527e4afc-4598-400f-8536-afa5324f0ba4/
3/3 at 2020-04-25 13:23:25.253047
dumped: 0
get_file:25,13:23:26:getRevision:164:YNTwNQ -- getRevision looping
test_uti:25,13:23:26:print_size:82:YNTwNQ -- ---------------Memory usage: 101532 (kb)---------------0 mins since start
test_uti:25,13:23:26:print_size:100:YNTwNQ -- /home/henry/pydocs/data/527e4afc-4598-400f-8536-afa5324f0ba4/
3/3 at 2020-04-25 13:23:26.290074
dumped: 0
test_uti:25,13:23:27:print_size:82:YNTwNQ -- ---------------Memory usage: 101532 (kb)---------------0 mins since start
test_uti:25,13:23:27:print_size:100:YNTwNQ -- /home/henry/pydocs/data/527e4afc-4598-400f-8536-afa5324f0ba4/
3/3 at 2020-04-25 13:23:27.333402
dumped: 0
get_file:25,13:23:27:getIdsRecursive:66:YNTwNQ -- getId task exiting
test_uti:25,13:23:28:print_size:82:YNTwNQ -- ---------------Memory usage: 101532 (kb)---------------0 mins since start
test_uti:25,13:23:28:print_size:100:YNTwNQ -- /home/henry/pydocs/data/527e4afc-4598-400f-8536-afa5324f0ba4/
3/3 at 2020-04-25 13:23:28.365073
dumped: 0
test_uti:25,13:23:28:tryGetQueue:211:YNTwNQ -- getRevisionwaiting 1 1
test_uti:25,13:23:28:tryGetQueue:211:YNTwNQ -- getRevisionwaiting 1 1
test_uti:25,13:23:28:tryGetQueue:211:YNTwNQ -- getRevisionwaiting 1 1
test_uti:25,13:23:29:print_size:82:YNTwNQ -- ---------------Memory usage: 101532 (kb)---------------0 mins since start
test_uti:25,13:23:29:print_size:100:YNTwNQ -- /home/henry/pydocs/data/527e4afc-4598-400f-8536-afa5324f0ba4/
3/3 at 2020-04-25 13:23:29.400271
dumped: 0
test_uti:25,13:23:30:print_size:82:YNTwNQ -- ---------------Memory usage: 101532 (kb)---------------0 mins since start
test_uti:25,13:23:30:print_size:100:YNTwNQ -- /home/henry/pydocs/data/527e4afc-4598-400f-8536-afa5324f0ba4/
3/3 at 2020-04-25 13:23:30.430515
dumped: 0
get_file:25,13:23:30:getIdsRecursive:66:YNTwNQ -- getId task exiting
get_file:25,13:23:31:getRevision:164:YNTwNQ -- getRevision looping
test_uti:25,13:23:31:print_size:82:YNTwNQ -- ---------------Memory usage: 101532 (kb)---------------0 mins since start
test_uti:25,13:23:31:print_size:100:YNTwNQ -- /home/henry/pydocs/data/527e4afc-4598-400f-8536-afa5324f0ba4/
3/3 at 2020-04-25 13:23:31.459164
dumped: 0
test_uti:25,13:23:32:print_size:82:YNTwNQ -- ---------------Memory usage: 101532 (kb)---------------0 mins since start
test_uti:25,13:23:32:print_size:100:YNTwNQ -- /home/henry/pydocs/data/527e4afc-4598-400f-8536-afa5324f0ba4/
3/3 at 2020-04-25 13:23:32.491291
dumped: 0
get_file:25,13:23:33:getRevision:169:YNTwNQ -- getRevision task exiting
get_file:25,13:23:33:getRevision:194:YNTwNQ -- getRevision task has ended, waiting for 3 seconds for all other tasks to finish
get_file:25,13:23:33:getRevision:169:YNTwNQ -- getRevision task exiting
get_file:25,13:23:33:getRevision:194:YNTwNQ -- getRevision task has ended, waiting for 3 seconds for all other tasks to finish
test_uti:25,13:23:33:print_size:82:YNTwNQ -- ---------------Memory usage: 101532 (kb)---------------0 mins since start
test_uti:25,13:23:33:print_size:100:YNTwNQ -- /home/henry/pydocs/data/527e4afc-4598-400f-8536-afa5324f0ba4/
3/3 at 2020-04-25 13:23:33.517257
dumped: 0
get_file:25,13:23:34:getRevision:164:YNTwNQ -- getRevision looping
test_uti:25,13:23:34:print_size:82:YNTwNQ -- ---------------Memory usage: 101532 (kb)---------------0 mins since start
test_uti:25,13:23:34:print_size:100:YNTwNQ -- /home/henry/pydocs/data/527e4afc-4598-400f-8536-afa5324f0ba4/
3/3 at 2020-04-25 13:23:34.545644
dumped: 0
test_uti:25,13:23:34:tryGetQueue:211:YNTwNQ -- getRevisionwaiting 1 1
test_uti:25,13:23:34:tryGetQueue:211:YNTwNQ -- getRevisionwaiting 1 1
get_file:25,13:23:35:getRevision:169:YNTwNQ -- getRevision task exiting
get_file:25,13:23:35:getRevision:194:YNTwNQ -- getRevision task has ended, waiting for 3 seconds for all other tasks to finish
test_uti:25,13:23:35:print_size:82:YNTwNQ -- ---------------Memory usage: 101532 (kb)---------------0 mins since start
test_uti:25,13:23:35:print_size:100:YNTwNQ -- /home/henry/pydocs/data/527e4afc-4598-400f-8536-afa5324f0ba4/
3/3 at 2020-04-25 13:23:35.578327
dumped: 0
get_file:25,13:23:35:getIdsRecursive:66:YNTwNQ -- getId task exiting
get_file:25,13:23:36:getRevision:197:YNTwNQ -- Close event has been set. Expect print task to finish soon
get_file:25,13:23:36:getRevision:197:YNTwNQ -- Close event has been set. Expect print task to finish soon
get_file:25,13:23:38:getRevision:169:YNTwNQ -- getRevision task exiting
get_file:25,13:23:38:getRevision:194:YNTwNQ -- getRevision task has ended, waiting for 3 seconds for all other tasks to finish
get_file:25,13:23:38:getRevision:197:YNTwNQ -- Close event has been set. Expect print task to finish soon
get_file:25,13:23:41:getRevision:197:YNTwNQ -- Close event has been set. Expect print task to finish soon
get_file:25,13:23:42:getRevision:169:YNTwNQ -- getRevision task exiting
get_file:25,13:23:42:getRevision:194:YNTwNQ -- getRevision task has ended, waiting for 3 seconds for all other tasks to finish
get_file:25,13:23:43:getRevision:194:YNTwNQ -- getRevision task has ended, waiting for 3 seconds for all other tasks to finish
get_file:25,13:23:44:getRevision:194:YNTwNQ -- getRevision task has ended, waiting for 3 seconds for all other tasks to finish
get_file:25,13:23:45:getRevision:197:YNTwNQ -- Close event has been set. Expect print task to finish soon
get_file:25,13:23:45:getRevision:194:YNTwNQ -- getRevision task has ended, waiting for 3 seconds for all other tasks to finish
get_file:25,13:23:46:getRevision:197:YNTwNQ -- Close event has been set. Expect print task to finish soon
get_file:25,13:23:46:getRevision:169:YNTwNQ -- getRevision task exiting
get_file:25,13:23:46:getRevision:194:YNTwNQ -- getRevision task has ended, waiting for 3 seconds for all other tasks to finish
get_file:25,13:23:47:getRevision:197:YNTwNQ -- Close event has been set. Expect print task to finish soon
get_file:25,13:23:48:getRevision:197:YNTwNQ -- Close event has been set. Expect print task to finish soon
get_file:25,13:23:49:getRevision:197:YNTwNQ -- Close event has been set. Expect print task to finish soon
get_file:25,13:23:51:getRevision:169:YNTwNQ -- getRevision task exiting
get_file:25,13:23:51:getRevision:194:YNTwNQ -- getRevision task has ended, waiting for 3 seconds for all other tasks to finish
get_file:25,13:23:54:getRevision:197:YNTwNQ -- Close event has been set. Expect print task to finish soon
get_file:25,13:23:54:start:232:YNTwNQ -- await gather revisions done
get_file:25,13:23:54:start:239:YNTwNQ -- cancelled throttler
get_file:25,13:23:54:loadFiles:294:YNTwNQ -- loop done
test_uti:25,13:23:54:dump_files:124:YNTwNQ -- pathed files at /home/henry/pydocs/data/527e4afc-4598-400f-8536-afa5324f0ba4/1.pathed, length 3
get_file:25,13:23:54:loadFiles:311:YNTwNQ -- dumped pickle files
sql.py:25,13:23:54:start:97:YNTwNQ -- STARTING SQL 527e4afc-4598-400f-8536-afa5324f0ba4 /home/henry/pydocs/data/527e4afc-4598-400f-8536-afa5324f0ba4/
sql.py:25,13:23:54:start:99:YNTwNQ -- setting sys except hook
sql.py:25,13:23:54:start:109:YNTwNQ -- Owner name: 527e4afc-4598-404 25 AprUdlUY8QWsg
sql.py:25,13:23:55:start:113:YNTwNQ -- Added owner row, name: 527e4afc-4598-404 25 AprUdlUY8QWsg id: 349
sql.py:25,13:23:55:start:126:YNTwNQ -- Finished loading pickles
sql.py:25,13:23:55:start:142:YNTwNQ -- File: 1NpTHMCkLa6lHL9Ok8a9hejyXihpujcQpVgSa7JNBP6s
sql.py:25,13:23:55:start:142:YNTwNQ -- File: 1JEcM-IFEodRvDg7EE9AntQ4wwOBTRXcDFqRK5SR2I08
sql.py:25,13:23:55:start:142:YNTwNQ -- File: 1LcO1aZmE6Jap4GF5ZpBGetjUSFeVBYg__DgWYlDwWY4
sql.py:25,13:23:55:start:159:YNTwNQ -- len of id map 3 len of files 3
sql.py:25,13:23:55:start:164:YNTwNQ -- starting bulk save
sql.py:25,13:23:55:adder:86:YNTwNQ -- flushing adder
configlo:25,13:23:55:handle_exception:81:YNTwNQ -- Custom Uncaught exception
Traceback (most recent call last):
  File "/home/henry/.virtualenvs/pydocs/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1247, in _execute_context
    self.dialect.do_execute(
  File "/home/henry/.virtualenvs/pydocs/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
pyodbc.DataError: ('22003', '[22003] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Arithmetic overflow error converting expression to data type datetime. (8115) (SQLExecDirectW)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "dsds.py", line 37, in <module>
    start()
  File "dsds.py", line 34, in start
    loadFiles(uid, workingPath, fileid, creds)
  File "/home/henry/pydocs/processing/get_files.py", line 317, in loadFiles
    processing.sql.start(USER_ID, _workingPath)
  File "/home/henry/pydocs/processing/sql.py", line 165, in start
    adder(lt_files, sess)
  File "/home/henry/pydocs/processing/sql.py", line 87, in adder
    sess.flush()
  File "/home/henry/.virtualenvs/pydocs/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2496, in flush
    self._flush(objects)
  File "/home/henry/.virtualenvs/pydocs/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2637, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/henry/.virtualenvs/pydocs/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/home/henry/.virtualenvs/pydocs/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/henry/.virtualenvs/pydocs/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2597, in _flush
    flush_context.execute()
  File "/home/henry/.virtualenvs/pydocs/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/home/henry/.virtualenvs/pydocs/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 586, in execute
    persistence.save_obj(
  File "/home/henry/.virtualenvs/pydocs/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 239, in save_obj
    _emit_insert_statements(
  File "/home/henry/.virtualenvs/pydocs/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 1135, in _emit_insert_statements
    result = cached_connections[connection].execute(
  File "/home/henry/.virtualenvs/pydocs/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 984, in execute
    return meth(self, multiparams, params)
  File "/home/henry/.virtualenvs/pydocs/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/henry/.virtualenvs/pydocs/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1097, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/henry/.virtualenvs/pydocs/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1287, in _execute_context
    self._handle_dbapi_exception(
  File "/home/henry/.virtualenvs/pydocs/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1481, in _handle_dbapi_exception
    util.raise_(
  File "/home/henry/.virtualenvs/pydocs/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/henry/.virtualenvs/pydocs/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1247, in _execute_context
    self.dialect.do_execute(
  File "/home/henry/.virtualenvs/pydocs/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DataError: (pyodbc.DataError) ('22003', '[22003] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Arithmetic overflow error converting expression to data type datetime. (8115) (SQLExecDirectW)')
[SQL: INSERT INTO files ([fileId], [lastModDate], parent_id, [isFile]) OUTPUT inserted.id VALUES (?, ?, ?, ?)]
[parameters: ('1NpTHMCkLa6lHL9Ok8a9hejyXihpujcQpVgSa7JNBP6s:25-13.506621UdlUY8QWsg', 1580798526504, 349, 1)]
(Background on this error at: http://sqlalche.me/e/9h9h)
configlo:25,13:23:57:handle_exception:85:YNTwNQ -- exiting! from sshook
